### PR TITLE
chore(release): new version

### PR DESCRIPTION
**Pull request by EinfachHans**

### CODE REVIEW

**Comment by erikramalho** [comment]
Please, update the file plugin.xml because the version inside it is 1.4.0 and doesn't match with NPM version :-)

**Comment by EinfachHans** [comment]
@erikramalho are there any issues when they not match?

**Comment by erikramalho** [comment]
hi @EinfachHans no issue at all, but it could confuses peolpe (includding me) because when you look at the package.json or perform a npm outdated operation it shows 1.6.0 version but when you run cordova plugin ls it shows 1.4.0.

**Comment by EinfachHans** [comment]
@erikramalho you're right that's confusing. The version in this plugin is incremented wie semantic release automatically. I will add a script for incrementing the one here as well

**Pull request merged**
